### ISSUE TITLE
ConcurrentModificationException caught

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-java#363] opened 2018-03-02 11:24 UTC
When preparing a demo, I occasionally got the following exception:

```
Exception in thread "jaeger.RemoteReporter-QueueProcessor" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at com.uber.jaeger.reporters.protocols.JaegerThriftSpanConverter.buildLogs(JaegerThriftSpanConverter.java:71)
	at com.uber.jaeger.reporters.protocols.JaegerThriftSpanConverter.convertSpan(JaegerThriftSpanConverter.java:53)
	at com.uber.jaeger.senders.ThriftSender.append(ThriftSender.java:70)
	at com.uber.jaeger.reporters.RemoteReporter$AppendCommand.execute(RemoteReporter.java:149)
	at com.uber.jaeger.reporters.RemoteReporter$QueueProcessor.run(RemoteReporter.java:182)
	at java.lang.Thread.run(Thread.java:748)
```

Not sure yet if relevant, but the LoggingReporter is being used in addition to the RemoteReporter.

**Comment by pavolloffay** [comment] 2018-03-02 11:49
What version of the client?

**Comment by jpkrohling** [comment] 2018-03-02 12:47
Current master

**Comment by pavolloffay** [comment] 2018-05-24 14:31
I am not sure how this could happen as the `span.getLogs()` returns an unmodifiable collection.

**Comment by jpkrohling** [comment] 2018-06-28 15:05
Seems related to #334

**Comment by bygui86** [comment] 2018-07-20 11:04
@pavolloffay please have a look on the issue #334 
I posted a sample-repo to reproduce the issue.
https://github.com/bygui86/spring-cloud-stream-kafka-jaeger

I hope this can help :)
I will continue my tests to find out something more ;)

**Comment by pavolloffay** [comment] 2018-07-20 11:41
This looks like a duplicate of #334. I will resolve it.

**Closed by pavolloffay** 2018-07-20 11:41 UTC
Labels: bug, help wanted
