### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by sherwoodzern** [jaegertracing/jaeger-client-java#625] opened 2019-05-08 23:37 UTC
## Requirement - what kind of business use case are you trying to solve?

Use openTracing and connect to the Current running tracer from the Istio Service Mesh

## Problem - what in Jaeger blocks you from solving the requirement?

Unable to get traces from the application.
2019.05.08 21:56:15 WARNING io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator Thread[nioEventLoopGroup-3-1,10,main]: Error when extracting SpanContext from carrier. Handling gracefully.
java.lang.ClassCastException: io.opentracing.propagation.TextMapExtractAdapter cannot be cast to io.opentracing.propagation.TextMap
	at io.jaegertracing.internal.propagation.TextMapCodec.extract(TextMapCodec.java:37)
	at io.jaegertracing.internal.PropagationRegistry$ExceptionCatchingExtractorDecorator.extract(PropagationRegistry.java:57)
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:217)
	at io.jaegertracing.internal.JaegerTracer.extract(JaegerTracer.java:63)
	at io.opentracing.util.GlobalTracer.extract(GlobalTracer.java:204)
	at io.helidon.webserver.RequestRouting.createRequestSpan(RequestRouting.java:133)
	at io.helidon.webserver.RequestRouting.route(RequestRouting.java:71)
	at io.helidon.webserver.netty.ForwardingHandler.channelRead0(ForwardingHandler.java:130)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Fix the ClassCastExceptions. There appears to be an issue with versions. I'm using the opentracing CDI and injecting the Traced and Tracer within the code. Everything is done through DI; therefore, I'm not instantiating any Tracer classes explicitly. It is all done through DI.

Current versions being used:
 <dependency>
            <groupId>io.opentracing</groupId>
            <artifactId>opentracing-api</artifactId>
            <version>0.33.0</version>
        </dependency>
        <dependency>
            <groupId>io.opentracing</groupId>
            <artifactId>opentracing-util</artifactId>
            <version>0.33.0</version>
        </dependency>
        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-cdi</artifactId>
            <version>0.1.0</version>
         </dependency>
         <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-tracerresolver</artifactId>
            <version>0.1.7</version>
         </dependency>
         <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-ejb</artifactId>
            <version>0.0.8</version>
         </dependency>

**Comment by yurishkuro** [comment] 2019-05-09 02:41
duplicate of #626, try using OT 0.32

**Closed by yurishkuro** 2019-05-09 02:41 UTC
