### ISSUE TITLE
Publishing to Nexus is failing

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#722] opened 2020-06-27 19:25 UTC
Release 1.3.0 failed to publish with the following error:

> Invalid POM: /io/jaegertracing/jaeger-thrift/1.3.0/jaeger-thrift-1.3.0.pom: Project name missing, Project description missing, Project URL missing, License information missing, SCM URL missing, Developer information missing

cc @pavolloffay @jpkrohling

**Comment by yurishkuro** [comment] 2020-06-27 19:32
After running `./gradlew publishToMavenLocal -PskipSigning=true` and comparing these files

* ~/.m2/repository/io/jaegertracing/jaeger-core/1.3.1-SNAPSHOT/jaeger-core-1.3.1-SNAPSHOT.pom
* ~/.m2/repository/io/jaegertracing/jaeger-client/1.3.1-SNAPSHOT/jaeger-client-1.3.1-SNAPSHOT.pom
* ~/.m2/repository/io/jaegertracing/jaeger-thrift/1.3.1-SNAPSHOT/jaeger-thrift-1.3.1-SNAPSHOT.pom

only jaeger-thrift has very differently looking (almost empty) pom file

cc @zhalas

**Comment by pavolloffay** [comment] 2020-06-29 08:44
Could you please past the content of the jaeger-thrift? Maybe it does not inherit settings from the parent.

The issue is most likely in this PR https://github.com/jaegertracing/jaeger-client-java/pull/704 by @zhalas

**Comment by yurishkuro** [comment] 2020-06-29 14:56
Do you mean content of the generated `jaeger-thrift.pom`?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.jaegertracing</groupId>
  <artifactId>jaeger-thrift</artifactId>
  <version>1.3.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <dependencies/>
</project>
```

**Comment by zhalas** [comment] 2020-06-29 16:24
The problem is that while publishing the shadow aritifact we also publish POM for it, and it's the shadow POM that is causing problems. It is indeed caused by #704. I'm trying to find some solution to this problem, but if it's blocking release revert may not be a bad idea.

**Comment by yurishkuro** [comment] 2020-06-29 16:34
@zhalas I'm ok to wait with the release until this is resolved.

**Comment by yurishkuro** [comment] 2020-06-30 00:58
It looks like POM issue is fixed, but publishing is still failing, I don't know why. The errors from Sonatype are like this:
```

typeId | RepositoryWritePolicy
-- | --
failureMessage | Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/io/jaegertracing/jaeger-tracerresolver/1.3.1/jaeger-tracerresolver-1.3.1-sources.jar'
failureMessage | Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/io/jaegertracing/jaeger-tracerresolver/1.3.1/jaeger-tracerresolver-1.3.1.pom'
failureMessage | Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/io/jaegertracing/jaeger-tracerresolver/1.3.1/jaeger-tracerresolver-1.3.1.jar'
failureMessage | Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/io/jaegertracing/jaeger-tracerresolver/1.3.1/jaeger-tracerresolver-1.3.1-javadoc.jar'
failureMessage | Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/io/jaegertracing/jaeger-thrift/1.3.1/jaeger-thrift-1.3.1-sources.jar'
failureMessage | Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/io/jaegertracing/jaeger-thrift/1.3.1/jaeger-thrift-1.3.1.jar'
failureMessage | Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/io/jaegertracing/jaeger-thrift/1.3.1/jaeger-thrift-1.3.1-shadow.jar'
```

I dropped all unclosed repositories before running the release, but it still failed.

@pavolloffay any thoughts?

**Comment by pavolloffay** [comment] 2020-06-30 07:44
It seems that the artifacts got into the central https://repo.maven.apache.org/maven2/io/jaegertracing/jaeger-client/

Could you please provide a link to the CI job with those messages? 

The release job for 1.3.1 failed https://travis-ci.org/github/jaegertracing/jaeger-client-java/jobs/703361828#L834 on closing the nexus repository. I have seen this before and artifacts always got into the central. I would ignore this error.

**Comment by yurishkuro** [comment] 2020-06-30 14:19
both 1.3.0 and 1.3.1 jobs were red

* https://travis-ci.org/github/jaegertracing/jaeger-client-java/builds/703361825
* https://travis-ci.org/github/jaegertracing/jaeger-client-java/builds/703338723

**Comment by zhalas** [comment] 2020-06-30 17:21
This looks strange. From the Sonatype logs you posted it looks like all the artifacts are uploaded more than once, but I don't know how #725 could cause that. If there are any issues I would expect them to be localized and affecting only shadow artifacts. I can try to look at publishing flow and see if I can find any problems (which may be hard to do without end-to-end publishing flow), or we can revert shadow publishing changes, try to improve them and merge later.

**Comment by yurishkuro** [comment] 2020-06-30 18:02
@zhalas I don't think it's related to your change. The gradle plugin has always been pretty weak in dealing with Sonatype.

**Closed** 2022-01-10 19:35 UTC
