### ISSUE TITLE
Investigate "warning: [options] bootstrap class path not set in conjunction with -source 1.7"

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-java#42] opened 2016-09-06 19:03 UTC

**Comment by vprithvi** [comment] 2016-09-20 20:39
It seems that this could be because of compiling under the java 8 compiler instead of the java 7 compiler http://stackoverflow.com/questions/16679593/gradle-compilejava-task-warning-options-bootstrap-class-path-not-set-in-conju

**Comment by alshopov** [comment] 2017-07-26 12:40
These messages are from the Oracle's javac:
```
public class HelloWorld{
    public static void main(String[] args){
	System.out.println("Hello, World!");
    }
}
```
```
$ javac -version
javac 1.8.0_131
```
```
$ javac -source 1.7 HelloWorld.java
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
```
```
$ javac -target 1.7 HelloWorld.java
javac: target release 1.7 conflicts with default source release 1.8
```
```
$ javac -source 1.7 -target 1.7 HelloWorld.java
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
```
A solution will be to force a 1.7 classpath during compilation even when using 1.8 javac:
```
$ CP=`ls /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home//jre/lib/*jar | tr '\n' ':'`
$ javac -cp $CP -bootclasspath $CP -source 1.7 -target 1.7 HelloWorld.java
```
The proper solution is to force JDK 1.7 on compilation if you insist on Java 7 compatibility.

Another solution will be to document that for the maintainer - that officially published jars must be built by JDK 7.

**Comment by 8Ozymandias** [comment] 2017-11-20 17:24
@alshopov  where exactly do you put:

"$ CP=`ls /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home//jre/lib/*jar | tr '\n' ':'`
$ javac -cp $CP -bootclasspath $CP -source 1.7 -target 1.7 HelloWorld.java"

**Comment by jpkrohling** [comment] 2018-04-20 09:32
Is this still relevant?

**Comment by yurishkuro** [comment] 2018-04-20 21:27
I'm still seeing at least this warning
```
> Task :jaeger-thrift:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
```

**Comment by jpkrohling** [comment] 2018-06-18 14:28
That's quite harmless for our use case, but updating to Java 8 makes it go away completely ;-)

I'm closing this but feel free to reopen if there's a real issue being caused by this.

**Closed by jpkrohling** 2018-06-18 14:28 UTC
